### ISSUE TITLE
Spelling on title is wrong

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [MaximUltimatum/ColdLogicRespiratory2016#1]
You can fix that in the repository settings. There's an option to rename it there, if you'd like.

**Comment by MaximUltimatum** [comment]
That was on purpose, Gabe [&#X1f60a]    pushing commits to the respiratory is now an inside joke. I can fix it if you'd like, though

**Comment by LivInTheLookingGlass** [comment]
Eh, if it works it works. Consider it closed. Take node of my edit to the
readme though.
