### ISSUE TITLE
Code should not be directly in autonomousPeriodic()/teleopPeriodic()

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [MaximUltimatum/ColdLogicRespiratory2016#4]
This is both a safety issue and a rules violation.

FIRST requires that we use their scheduler, and for good reason. If I remember correctly, putting code directly in the periodic method makes disabling the robot more difficult for them. In certain situations you/they **need it shut down now** and this could interfere with that.

_Please_ take example from previous years instead of going forward on your own. There's already a good structure set up in the team's repository. It would be very easy to migrate the code you have so far to that platform.

**Comment by MaximUltimatum** [comment]
Got it

**Comment by MaximUltimatum** [comment]
Should be O.K., I moved it too autonomous command and drive command
